name: noise-classification-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - git
  - ffmpeg
  - numpy
  - pandas
  - tqdm
  - matplotlib
  - scikit-learn=1.3.0
  - librosa=0.10.1
  - soundfile
  - onnx
  - pip
  - pip:
      - torch
      - mlflow==2.2.2
      - optuna==3.5.0